#pragma once

#undef STARTUP_SONG

#undef ANALOG_JOYSTICK_X_AXIS_PIN
#undef ANALOG_JOYSTICK_Y_AXIS_PIN

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27

#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_INVERT_Y_RIGHT

#undef POINTING_DEVICE_INVERT_X
